# Generated by Django 3.1.1 on 2020-09-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='awards_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='awards_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='biography_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='biography_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='gender_en',
            field=models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='gender_ru',
            field=models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='name_en',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='name_ru',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='surname_en',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='surname_ru',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='tagline_en',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='tagline_ru',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='awards_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='awards_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='biography_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='biography_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='gender_en',
            field=models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='gender_ru',
            field=models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='name_en',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='name_ru',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='surname_en',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='surname_ru',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
