# Generated by Django 3.1.1 on 2020-09-24 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_actor_producer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
