# Generated by Django 3.1.1 on 2020-09-24 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_genre_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('USA', 'USA'), ('FRA', 'France'), ('GER', 'Germany'), ('RUS', 'Russia')], max_length=20)),
                ('date_premiere', models.DateField()),
                ('box_office', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MovieShot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='movie_shots/')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_shots', related_query_name='movie_shots_query', to='MainApp.movie')),
            ],
            options={
                'verbose_name': 'Movie shot',
                'verbose_name_plural': 'Movie shots',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='country_premiere',
            field=models.ManyToManyField(related_name='movies', related_query_name='movies_query', to='MainApp.Country'),
        ),
    ]
