# Generated by Django 3.1.1 on 2020-09-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_auto_20200924_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieshot',
            name='description',
        ),
        migrations.AddField(
            model_name='movieshot',
            name='additional_image',
            field=models.ImageField(default='', upload_to='additional_films/'),
        ),
        migrations.AddField(
            model_name='movieshot',
            name='background_image',
            field=models.ImageField(default='', upload_to='background_image/'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='icon',
            field=models.ImageField(upload_to='%(class)s_icon'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.ImageField(upload_to='%(class)s_image'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='icon',
            field=models.ImageField(upload_to='%(class)s_icon'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='image',
            field=models.ImageField(upload_to='%(class)s_image'),
        ),
    ]
