# Generated by Django 3.1.1 on 2020-09-27 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_auto_20200924_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['date_premiere'], 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.RemoveField(
            model_name='genre',
            name='category',
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', related_query_name='movies_query', to='MainApp.category'),
        ),
    ]
